### ISSUE TITLE
音声アップロード機能実装の調査

### ISSUE THREAD

**Issue by koheitakahashi** [tramaru/hikido#19]

**Comment by otegami** [comment]
## Issue

#18 # 19 の技術調査として

## やったこと
Discord Bot で、ユーザーの音声を録音し S3 にアップロードすること
- Discord Bot の作成
	- 会話中の Channel に参加・離脱する機能
	- 会話を録音する機能
	- 録音した会話を S3 にアップロードする機能
- 下記のサンプルコードを用意しました
	- hikido 配下に移すのも良さそう
	- ref: https://github.com/otegami/hikido_bot

## 分かったこと
### Discord Bot について

1. 事前に対応できるコマンドを登録しておく必要があること
2. 設定したコマンドに対応するようのプロセスを随時立てておく必要があること

#### 1. 事前に対応できるコマンドを登録しておく必要があること
- discord.js 側のチュートリアルでコマンドの作成方法や登録方法を解説してくれていてわかりやすかったです
    - ref: https://discordjs.guide/interactions/slash-commands.html

#### 2. 設定したコマンドに対応するようのプロセスを随時立てておく必要があること
- Discord Bot 側のコマンドは REST API で登録できるようになっているが、コマンドの処理は各自でプロセスを立てて対応する必要がある

## 議論したい内容

### 設定したコマンドに対応するようのプロセスを随時立てておく必要があること
- express or fastify などが軽量で比較的に簡単に別プロセスを立ち上げられそう
- Next.js 側でも Custom Server 機能というのがあるみたい
    - https://nextjs.org/docs/advanced-features/custom-server 
    - https://qiita.com/SoraKumo/items/67eb3a8076c6a2f008d7

**Comment by otegami** [comment]
### お話したこと
- express で対応する方針に決まりました
    - Next.js が公式でドキュメントも用意してくれているため
- 課題は音声データを一つのファイルに集約したいこと
    - 話者を区別しない方針で進めてみる
    - ファイルを統合するイメージ (時系列順)

**Comment by otegami** [comment]
#21 で実装することになったため、こちらの Issue は完了！
