### ISSUE TITLE
録音・アップロードする discord bot を作成する

### ISSUE THREAD

**Issue by koheitakahashi** [tramaru/hikido#21]

**Comment by otegami** [comment]
やること
- express で対応する方針に決まりました
    - Next.js が公式でドキュメントも用意してくれているため
- 課題は音声データを一つのファイルに集約したいこと
    - 話者を区別しない方針で進めてみる
        - ファイルを統合するイメージ (時系列順)

**Comment by otegami** [comment]
下記のリポジトリで、音声データを一つにまとめる機能の実装を行いました。
8/23 のモブプロで hikido_bot を hikido リポジトリに移行する作業を行います。
ref: https://github.com/otegami/hikido_bot

**Comment by otegami** [comment]
https://github.com/tramaru/hikido/pull/29 にて対応済み🙌
