### ISSUE TITLE
discord_bot 側に prisma を入れる

### ISSUE THREAD

**Issue by koheitakahashi** [tramaru/hikido#24]

**Comment by koheitakahashi** [comment]
併せて discord_bot と next app の prisma の migration/schema 共有方法を考えていただく。

以下話した案。
- ルートディレクトリに prisma ディレクトリを作る
- リポジトリを分けて、prisma ディレクトリを gitsubmodules にする

**Comment by otegami** [comment]
https://github.com/tramaru/hikido/pull/39 にて対応
