### ISSUE TITLE
custom server の調査

### ISSUE THREAD

**Issue by koheitakahashi** [tramaru/hikido#25]

**Comment by otegami** [comment]
## 結論
- Next.js の Custom Server は、Discort Bot を起動しておく別 Process を立てるの用途ではなさそう
    - ^とりあえず、児玉が現時点で理解している範囲です 

## 調べたこと
> カスタム Next.js サーバーはカスタムされたサーバーパターンを利用するために 100% プログラムで制御してサーバーを起動することを可能にします。ほとんどの場合必要ではありませんが、完全なカスタマイズのために利用可能です。

- 公式サイトには上記のように書かれております。
    - 実際の公式サイトなどで利用される例
        - 複数の Next.js で作られたアプリへのルーティングを制御するため
        - Next.js のルーティングに沿っていない場合に、独自にルーティングしてあげるため
        - Middleware に何かを追加するため
- https://nextjs-ja-translation-docs.vercel.app/docs/advanced-features/custom-server

## 今後の方針
- 本番環境では、以前 SoundLinks でやられていたように、サービスを 2 つ作ってあげる方針で行くのが良さそうかなと考えています。

### 相談したいこと
- 今後の方針に関しての相談をしたいです
- また、上記の方針で進めていって問題がない場合
    - 管理しやすいようにディレクトリ構成を下記のように変更すると良さそうかなと考えています
```
- hikido
    - next
    - bot 
```

**Comment by otegami** [comment]
決まったこと
- hikido と同じリポジトリで Discord Bot も管理する
- Heroku で動かすことになりました
    - DB に関しては共有します
    - migration に関しては、symlink で管理します
