### ISSUE TITLE
Heroku に hikido discord bot をデプロイ

### ISSUE THREAD

**Issue by otegami** [tramaru/hikido#28]

**Comment by otegami** [comment]
https://github.com/tramaru/hikido/pull/45

**Comment by koheitakahashi** [comment]
tips ですが、 `development` という所で、該当の issue と PR を紐付けることができるので、https://github.com/tramaru/hikido/issues/28#issuecomment-1264309577 のように issue と PR の紐付けをコメント残さなくて良くなります〜。

こんな感じに。
![CleanShot 2022-10-02 at 17 34 47](https://user-images.githubusercontent.com/51867807/193445449-d1fdde71-54dc-40ae-beb0-b38d02441cbd.png)
